"""Initial migration

Revision ID: be9a45d59069
Revises: 8758f38f0950
Create Date: 2026-01-30 01:36:56.246550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9a45d59069'
down_revision = '8758f38f0950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
